import type { AssetDefinition } from '../types/asset.js';

export const ANIMAL_ASSETS: AssetDefinition[] = [
  {
    id: 'animal-cow-yellow',
    category: 'animals',
    name: 'Bò Vàng Nam Bộ (Vietnamese Yellow Cow)',
    texture: '/farm/sprites/sprite_050_cid99.png',
    visualBounds: { width: 32, height: 32 },
    footprint: { tileWidth: 1, tileHeight: 1 },
    anchor: { x: 0.5, y: 1.0 },
    collision: { solid: true },
    tags: ['animal', 'cow', 'livestock', 'rural', 'vietnamese', 'pasture'],
    styleVersion: 1,
    animation: {
      type: 'spritesheet',
      frameWidth: 32,
      frameHeight: 32,
      frameCount: 4,
      frameRate: 6,
      directions: ['down', 'up', 'left', 'right'],
    },
  },
  {
    id: 'animal-chicken-rooster',
    category: 'animals',
    name: 'Gà Tre Thả Vườn (Free-range Rooster)',
    texture: '/farm/sprites/sprite_051_cid16.png',
    visualBounds: { width: 32, height: 32 },
    footprint: { tileWidth: 1, tileHeight: 1 },
    anchor: { x: 0.5, y: 1.0 },
    collision: { solid: false },
    tags: ['animal', 'chicken', 'poultry', 'livestock', 'rural'],
    styleVersion: 1,
    animation: {
      type: 'spritesheet',
      frameWidth: 32,
      frameHeight: 32,
      frameCount: 4,
      frameRate: 8,
      directions: ['down', 'up', 'left', 'right'],
    },
  },
  {
    id: 'animal-pig-muddy',
    category: 'animals',
    name: 'Heo Mọi Tắm Bùn (Muddy Farm Pig)',
    texture: '/farm/sprites/pig_mud_pen.png',
    visualBounds: { width: 32, height: 32 },
    footprint: { tileWidth: 1, tileHeight: 1 },
    anchor: { x: 0.5, y: 1.0 },
    collision: { solid: true },
    tags: ['animal', 'pig', 'livestock', 'mud', 'farm'],
    styleVersion: 1,
    animation: {
      type: 'spritesheet',
      frameWidth: 32,
      frameHeight: 32,
      frameCount: 4,
      frameRate: 6,
      directions: ['down', 'up', 'left', 'right'],
    },
  },
];
