import type { AssetDefinition } from '../types/asset.js';

export const BUILDING_ASSETS: AssetDefinition[] = [
  {
    id: 'building-farmhouse-rural',
    category: 'buildings',
    name: 'Nhà Cấp 4 Mái Ngói Đồng Nai (Rural Farmhouse)',
    texture: '/farm/sprites/farm_barn_main.png',
    visualBounds: { width: 128, height: 128 },
    footprint: { tileWidth: 4, tileHeight: 2, offsetY: 2 },
    anchor: { x: 0.5, y: 1.0 },
    collision: { solid: true },
    depthOffset: 64,
    tags: ['building', 'house', 'rural', 'farmhouse', 'farm', 'vietnamese', 'roof-tile'],
    styleVersion: 1,
  },
  {
    id: 'building-shop-bac-sau',
    category: 'buildings',
    name: 'Tiệm Tạp Hóa Nông Sản Bác Sáu (Produce Stall)',
    texture: '/farm/sprites/shop_bac_sau_stall.png',
    visualBounds: { width: 96, height: 96 },
    footprint: { tileWidth: 3, tileHeight: 2, offsetY: 1 },
    anchor: { x: 0.5, y: 1.0 },
    collision: { solid: true },
    depthOffset: 64,
    tags: ['building', 'shop', 'stall', 'market', 'commercial', 'farm', 'vietnamese'],
    styleVersion: 1,
  },
  {
    id: 'building-chicken-coop',
    category: 'buildings',
    name: 'Chuồng Nuôi Gà Thả Vườn (Chicken Coop)',
    texture: '/farm/sprites/chicken_coop.png',
    visualBounds: { width: 64, height: 64 },
    footprint: { tileWidth: 2, tileHeight: 1, offsetY: 1 },
    anchor: { x: 0.5, y: 1.0 },
    collision: { solid: true },
    depthOffset: 32,
    tags: ['building', 'coop', 'chicken', 'livestock', 'farm'],
    styleVersion: 1,
  },
  {
    id: 'building-silo-grain',
    category: 'buildings',
    name: 'Kho Thùng Chứa Thóc Lúa (Grain Silo)',
    texture: '/farm/sprites/silo_grain_warehouse.png',
    visualBounds: { width: 64, height: 96 },
    footprint: { tileWidth: 2, tileHeight: 2, offsetY: 1 },
    anchor: { x: 0.5, y: 1.0 },
    collision: { solid: true },
    depthOffset: 64,
    tags: ['building', 'silo', 'warehouse', 'storage', 'farm'],
    styleVersion: 1,
  },
];
