import type { AssetDefinition } from '../types/asset.js';

export const PROP_ASSETS: AssetDefinition[] = [
  {
    id: 'prop-fence-bamboo',
    category: 'props',
    name: 'Hàng Rào Tre Nông Thôn (Bamboo Fence)',
    texture: '/farm/sprites/sprite_024_cid144.png',
    visualBounds: { width: 32, height: 32 },
    footprint: { tileWidth: 1, tileHeight: 1 },
    anchor: { x: 0.5, y: 1.0 },
    collision: { solid: true },
    tags: ['fence', 'bamboo', 'barrier', 'boundary', 'vietnamese', 'rural'],
    styleVersion: 1,
  },
  {
    id: 'prop-water-jar-ceramic',
    category: 'props',
    name: 'Lu Sành Hứng Nước Mưa (Ceramic Rainwater Jar)',
    texture: '/farm/sprites/sprite_023_cid147.png',
    visualBounds: { width: 32, height: 32 },
    footprint: { tileWidth: 1, tileHeight: 1 },
    anchor: { x: 0.5, y: 1.0 },
    collision: { solid: true },
    tags: ['prop', 'jar', 'ceramic', 'water', 'lu-sanh', 'vietnamese', 'traditional'],
    styleVersion: 1,
  },
  {
    id: 'prop-lamp-post-rustic',
    category: 'props',
    name: 'Đèn Đường Gỗ Mộc (Rustic Wooden Lamp Post)',
    texture: '/farm/sprites/sprite_022_cid87.png',
    visualBounds: { width: 32, height: 64 },
    footprint: { tileWidth: 1, tileHeight: 1 },
    anchor: { x: 0.5, y: 1.0 },
    collision: { solid: true },
    tags: ['prop', 'lamp', 'light', 'wooden', 'night', 'lighting'],
    styleVersion: 1,
  },
  {
    id: 'prop-signpost-wooden',
    category: 'props',
    name: 'Bảng Chỉ Dẫn Bằng Gỗ (Wooden Signpost)',
    texture: '/farm/sprites/sprite_021_cid49.png',
    visualBounds: { width: 32, height: 32 },
    footprint: { tileWidth: 1, tileHeight: 1 },
    anchor: { x: 0.5, y: 1.0 },
    collision: { solid: true },
    tags: ['prop', 'sign', 'direction', 'wooden', 'info'],
    styleVersion: 1,
  },
];
