import type { AssetDefinition } from '../types/asset.js';

export const TERRAIN_ASSETS: AssetDefinition[] = [
  {
    id: 'terrain-grass-meadow',
    category: 'terrain',
    name: 'Cỏ Đồng Quê (Meadow Grass)',
    texture: '/farm/tiled/sprout_tileset.png',
    visualBounds: { width: 32, height: 32 },
    footprint: { tileWidth: 1, tileHeight: 1 },
    anchor: { x: 0.5, y: 0.5 },
    collision: { solid: false },
    tags: ['grass', 'meadow', 'nature', 'ground', 'rural', 'vietnamese'],
    styleVersion: 1,
  },
  {
    id: 'terrain-soil-loam',
    category: 'terrain',
    name: 'Đất Nông Trại Màu Mỡ (Tilled Loam)',
    texture: '/farm/tiled/sprout_tileset.png',
    visualBounds: { width: 32, height: 32 },
    footprint: { tileWidth: 1, tileHeight: 1 },
    anchor: { x: 0.5, y: 0.5 },
    collision: { solid: false },
    tags: ['soil', 'loam', 'dirt', 'ground', 'farm', 'fertile'],
    styleVersion: 1,
  },
  {
    id: 'terrain-water-pond',
    category: 'terrain',
    name: 'Mặt Nước Ao Kênh (Canal / Pond Water)',
    texture: '/farm/tiled/sprout_tileset.png',
    visualBounds: { width: 32, height: 32 },
    footprint: { tileWidth: 1, tileHeight: 1 },
    anchor: { x: 0.5, y: 0.5 },
    collision: { solid: true },
    tags: ['water', 'canal', 'pond', 'river', 'aquatic', 'liquid'],
    styleVersion: 1,
  },
  {
    id: 'terrain-cliff-edge',
    category: 'terrain',
    name: 'Vách Bờ Đất / Bờ Kè (Canal Bank Cliff)',
    texture: '/farm/tiled/sprout_tileset.png',
    visualBounds: { width: 32, height: 32 },
    footprint: { tileWidth: 1, tileHeight: 1 },
    anchor: { x: 0.5, y: 0.5 },
    collision: { solid: true },
    tags: ['cliff', 'edge', 'bank', 'barrier'],
    styleVersion: 1,
  },
];
