import type { AssetDefinition } from '../types/asset.js';

export const VEGETATION_ASSETS: AssetDefinition[] = [
  {
    id: 'tree-mango-large',
    category: 'vegetation',
    name: 'Cây Xoài Cổ Thụ (Large Mango Tree)',
    texture: '/farm/sprites/farm_barn_main.png',
    visualBounds: { width: 64, height: 96 },
    footprint: { tileWidth: 2, tileHeight: 1, offsetY: 2 },
    anchor: { x: 0.5, y: 1.0 },
    collision: { solid: true },
    depthOffset: 32,
    tags: ['tree', 'mango', 'tropical', 'fruit', 'nature', 'vietnamese', 'dong-nai'],
    styleVersion: 1,
  },
  {
    id: 'tree-bamboo-cluster',
    category: 'vegetation',
    name: 'Bụi Tre Làng (Bamboo Cluster)',
    texture: '/farm/sprites/sprite_028_cid48.png',
    visualBounds: { width: 32, height: 64 },
    footprint: { tileWidth: 1, tileHeight: 1, offsetY: 1 },
    anchor: { x: 0.5, y: 1.0 },
    collision: { solid: true },
    depthOffset: 32,
    tags: ['tree', 'bamboo', 'vietnamese', 'rural', 'hedge', 'foliage'],
    styleVersion: 1,
  },
  {
    id: 'tree-banana-clump',
    category: 'vegetation',
    name: 'Bụi Chuối Vườn (Banana Tree Clump)',
    texture: '/farm/sprites/sprite_027_cid86.png',
    visualBounds: { width: 64, height: 64 },
    footprint: { tileWidth: 2, tileHeight: 1, offsetY: 1 },
    anchor: { x: 0.5, y: 1.0 },
    collision: { solid: true },
    depthOffset: 32,
    tags: ['tree', 'banana', 'tropical', 'vietnamese', 'garden'],
    styleVersion: 1,
  },
  {
    id: 'flower-wild-bush',
    category: 'vegetation',
    name: 'Bụi Hoa Dại Ven Đường (Wildflower Bush)',
    texture: '/farm/sprites/sprite_059_cid7.png',
    visualBounds: { width: 32, height: 32 },
    footprint: { tileWidth: 1, tileHeight: 1 },
    anchor: { x: 0.5, y: 1.0 },
    collision: { solid: false },
    tags: ['flower', 'bush', 'wildflower', 'decoration', 'nature'],
    styleVersion: 1,
  },
];
