import type { ItemDefinitionSeed } from './items.js';

/** All pieces use the ordinary server-priced purchase and placement flow. */
export const GEN_Z_FURNITURE: ItemDefinitionSeed[] = [
  {
    id: 'furn_capybara',
    type: 'furniture',
    sprite: 'capybara:#c6a17c',
    size: { w: 2, h: 2 },
    decor: 6,
    name: 'Ghế Lười Capy Không Vội',
    rarity: 'rare',
    coinPrice: 520,
    description: 'Capy đội quýt, ngồi im trước mọi deadline. Ghế lười hình capybara, không phải thú nuôi.',
  },
  {
    id: 'furn_mushroom',
    type: 'furniture',
    sprite: 'mushroom:#dba19b',
    size: { w: 1, h: 1 },
    decor: 3,
    name: 'Đèn Nấm Mặt Ngơ',
    rarity: 'common',
    coinPrice: 140,
    description: 'Đèn trang trí hình nấm pastel. Nhìn hơi ngơ nhưng rất biết tạo mood.',
  },
  {
    id: 'furn_boba',
    type: 'furniture',
    sprite: 'boba:#cfb792',
    size: { w: 1, h: 1 },
    decor: 3,
    name: 'Trà Sữa Size Tinh Thần',
    rarity: 'common',
    coinPrice: 120,
    description: 'Mô hình ly trà sữa khổng lồ. Không uống được, nhưng nhìn là thấy được chữa lành.',
  },
  {
    id: 'furn_mirror',
    type: 'furniture',
    sprite: 'mirror:#ad9ac2',
    size: { w: 1, h: 2 },
    decor: 5,
    name: 'Gương OOTD Uốn Éo',
    rarity: 'rare',
    coinPrice: 380,
    description: 'Gương đứng viền tím lượn sóng. Một góc chụp outfit rất có thái độ.',
  },
  {
    id: 'furn_duck_plush',
    type: 'furniture',
    sprite: 'duckplush:#e8cf83',
    size: { w: 1, h: 1 },
    decor: 3,
    name: 'Vịt Bông Lowkey',
    rarity: 'common',
    coinPrice: 95,
    description: 'Vịt bông đeo kính đen. Không nói nhiều, chỉ âm thầm chiếm spotlight.',
  },
  {
    id: 'furn_cloud',
    type: 'furniture',
    sprite: 'cloud:#d5deea',
    size: { w: 2, h: 1 },
    decor: 4,
    name: 'Ghế Mây Lười Rep',
    rarity: 'rare',
    coinPrice: 340,
    description: 'Ghế đôn hình mây với nụ cười tỉnh bơ. Seen rồi nhưng đang chill.',
  },
  {
    id: 'furn_desk',
    type: 'furniture',
    sprite: 'desk:#b8a8cc',
    size: { w: 2, h: 2 },
    decor: 6,
    name: 'Bàn Deadline 23:59',
    rarity: 'rare',
    coinPrice: 680,
    description:
      'Bàn setup có màn hình pastel, bàn phím và cốc cà phê. Deadline dí nhưng góc làm việc phải đẹp.',
  },
  {
    id: 'furn_touch_grass',
    type: 'furniture',
    sprite: 'sign_touchgrass:#b6a0bd',
    size: { w: 2, h: 1 },
    decor: 4,
    name: 'Biển Touch Grass',
    rarity: 'common',
    coinPrice: 180,
    description:
      'Biển trang trí tự đứng nhắc bạn ra ngoài chạm cỏ. Có hình cây để khỏi quên cỏ trông thế nào.',
  },
  {
    id: 'furn_rug_smile',
    type: 'furniture',
    sprite: 'rug_smile:#dbc67f',
    size: { w: 2, h: 2 },
    decor: 4,
    name: 'Thảm Cười Hề Hề',
    rarity: 'common',
    coinPrice: 190,
    description: 'Thảm tròn mặt cười hơi hề. Đặt dưới ghế hoặc bàn để góc chill bớt nghiêm túc.',
  },
  {
    id: 'furn_rug_checker',
    type: 'furniture',
    sprite: 'rug_checker:#93ab8e',
    size: { w: 3, h: 2 },
    decor: 5,
    name: 'Thảm Caro Matcha',
    rarity: 'rare',
    coinPrice: 320,
    description: 'Caro xanh matcha và kem. Một chiếc nền xịn để hội đồ pastel đứng chung khung hình.',
  },
  {
    id: 'furn_snack_cart',
    type: 'furniture',
    sprite: 'snackcart:#9db9ab',
    size: { w: 1, h: 2 },
    decor: 5,
    name: 'Xe Snack Cứu Deadline',
    rarity: 'rare',
    coinPrice: 360,
    description: 'Xe đẩy ba tầng đầy bánh và nước mô hình. Kho tiếp tế tinh thần cho những hôm não loading.',
  },
];

export const GEN_Z_FURNITURE_IDS = new Set(GEN_Z_FURNITURE.map((item) => item.id));
