export const RESIDENT_QUESTS = [
  {
    id: 'welcome',
    chapter: 'Người mới đến phố',
    name: 'Một ngày tự lập',
    metric: 'jobs',
    target: 3,
    coin: 80,
    title: 'Cư dân mới',
    description: 'Hoàn thành 3 công việc câu cá, giao hàng hoặc pha chế.',
  },
  {
    id: 'worker',
    chapter: 'Người mới đến phố',
    name: 'Quen đường quen phố',
    metric: 'jobs',
    target: 15,
    coin: 160,
    title: 'Người thạo phố',
    description: 'Hoàn thành tổng cộng 15 công việc.',
  },
  {
    id: 'angler',
    chapter: 'Cần thủ Đồng Nai',
    name: 'Những trang đầu sổ cá',
    metric: 'species',
    target: 5,
    coin: 100,
    title: 'Bạn của dòng sông',
    description: 'Khám phá 5 loài cá khác nhau.',
  },
  {
    id: 'collector',
    chapter: 'Cần thủ Đồng Nai',
    name: 'Kho báu Đồng Nai',
    metric: 'species',
    target: 20,
    coin: 250,
    title: 'Nhà sưu tầm cá',
    description: 'Khám phá 20 loài cá khác nhau.',
  },
  {
    id: 'gardener',
    chapter: 'Nhà vườn',
    name: 'Chuyến hàng đầu mùa',
    metric: 'contracts',
    target: 1,
    coin: 100,
    title: 'Nhà vườn tập sự',
    description: 'Giao một hợp đồng tại tiệm Bác Sáu.',
  },
  {
    id: 'supplier',
    chapter: 'Nhà vườn',
    name: 'Mối quen Bác Sáu',
    metric: 'contracts',
    target: 10,
    coin: 250,
    title: 'Nhà cung ứng',
    description: 'Hoàn thành 10 hợp đồng nông sản.',
  },
  {
    id: 'cook',
    chapter: 'Khách quen',
    name: 'Bữa cơm của phố',
    metric: 'orders',
    target: 1,
    coin: 80,
    title: 'Đầu bếp tập sự',
    description: 'Nấu và giao một đơn món ăn từ bếp Cơm Gà 68.',
  },
  {
    id: 'chef',
    chapter: 'Khách quen',
    name: 'Hương vị thân quen',
    metric: 'orders',
    target: 10,
    coin: 200,
    title: 'Đầu bếp khu phố',
    description: 'Giao thành công 10 đơn món ăn.',
  },
  {
    id: 'cue',
    chapter: 'Tay cơ của phố',
    name: 'Trận thắng đầu tiên',
    metric: 'wins',
    target: 1,
    coin: 80,
    title: 'Tay cơ mới',
    description: 'Thắng một trận bida với người chơi khác.',
  },
  {
    id: 'champion',
    chapter: 'Tay cơ của phố',
    name: 'Đường cơ vững vàng',
    metric: 'wins',
    target: 10,
    coin: 200,
    title: 'Tay cơ H2S',
    description: 'Thắng 10 trận bida với người chơi khác.',
  },
] as const;
export const RESIDENT_RECIPES = [
  {
    id: 'egg_rice',
    name: 'Cơm trứng cà chua',
    output: 'meal_egg_rice',
    ingredients: [
      { id: 'crop_rice_harvest', quantity: 2 },
      { id: 'yield_egg', quantity: 1 },
      { id: 'crop_tomato_harvest', quantity: 1 },
    ],
    reward: 150,
    destination: 'cybernet',
    customer: 'Cyber HNT',
    unlockOrders: 0,
  },
  {
    id: 'sweet_corn',
    name: 'Sữa bắp nhà vườn',
    output: 'meal_sweet_corn',
    ingredients: [
      { id: 'crop_corn_harvest', quantity: 2 },
      { id: 'yield_milk', quantity: 1 },
    ],
    reward: 390,
    destination: 'university',
    customer: 'Đại học',
    unlockOrders: 1,
  },
  {
    id: 'fish_rice',
    name: 'Cơm cá kho',
    output: 'meal_fish_rice',
    ingredients: [
      { id: 'crop_rice_harvest', quantity: 2 },
      { id: 'fish_pond_tra_harvest', quantity: 1 },
      { id: 'crop_chili_harvest', quantity: 1 },
    ],
    reward: 210,
    destination: 'company',
    customer: 'Công ty',
    unlockOrders: 3,
  },
] as const;
